# Generated by Django 5.2.16 on 2026-07-19 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_language', models.CharField(blank=True, max_length=30)),
                ('dominant_emotion', models.CharField(blank=True, max_length=50)),
                ('detected_genre', models.CharField(blank=True, max_length=100)),
                ('keywords', models.JSONField(default=list)),
                ('timeline', models.JSONField(default=list)),
                ('analyzed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='stories.story')),
            ],
        ),
    ]
