# Generated by Django 5.2.16 on 2026-07-20 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_listeninghistory'),
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendationhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='input_text',
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='songs',
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='detected_emotion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='detected_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='detected_language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.playlist'),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='prompt',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
