# Generated by Django 5.2.16 on 2026-07-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='spotify_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='song',
            name='album_cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.language'),
        ),
        migrations.AlterField(
            model_name='song',
            name='mood',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.singer'),
        ),
    ]
