# Generated by Django 5.2.16 on 2026-07-20 02:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_song_spotify_id_remove_song_youtube_id_and_more'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-popularity', 'title']},
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='song',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='Example: dQw4w9WgXcQ', max_length=20),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stories.story'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='song',
            name='popularity',
            field=models.IntegerField(default=50),
        ),
    ]
